### ISSUE TITLE
Error when attempting to build jupyter-book (pdflatex) when using sphinxnotes-strike extension

### ISSUE THREAD

**Issue by rappdw** [sphinx-notes/strike#1]
Here's the log:
```
# Sphinx version: 4.4.0
# Python version: 3.10.0 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:
#   MP4._Designs/Data_Cleanroom_Designs/SageMaker_Training_Design
#   MP4._Designs/Inference_Network_Architecture
#   MP4._Designs/Vendor_Eval_VPC_DLP_
#   MP5._ML_Platform_Shared_Responsibility_Model
#   MP6._ML_Platform_Change_Process
#   
#   resolving references...
#   done
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.4.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinx_togglebutton (0.3.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_togglebutton/__init__.py
#   sphinx_copybutton (0.5.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_copybutton/__init__.py
#   myst_nb (0.13.2) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/myst_nb/__init__.py
#   jupyter_book (0.12.2) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/jupyter_book/__init__.py
#   sphinx_thebe (0.1.1) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_thebe/__init__.py
#   sphinx_comments (0.0.3) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_comments/__init__.py
#   sphinx_external_toc (0.2.4) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_external_toc/__init__.py
#   sphinx.ext.intersphinx (4.4.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/ext/intersphinx.py
#   sphinx_panels (0.6.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_panels/__init__.py
#   sphinx_book_theme (unknown version) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_book_theme/__init__.py
#   sphinxcontrib.drawio (0.0.14) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxcontrib/drawio/__init__.py
#   sphinx.ext.graphviz (4.4.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/ext/graphviz.py
#   sphinxnotes.strike (1.0) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinxnotes/strike/__init__.py
#   sphinx_jupyterbook_latex (unknown version) from /opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx_jupyterbook_latex/__init__.py
Traceback (most recent call last):
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/jupyter_book/sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/builders/latex/__init__.py", line 308, in write
    docwriter.write(doctree, destination)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/writers/latex.py", line 99, in translate
    self.document.walkabout(visitor)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 15 more times]
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/sphinx/util/docutils.py", line 520, in dispatch_departure
    super().dispatch_departure(node)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 2008, in dispatch_departure
    return method(node)
  File "/opt/miniconda3/envs/platform-docs/lib/python3.10/site-packages/docutils/nodes.py", line 2030, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: strike_node
```

**Comment by SilverRainZ** [comment]
Yes, latex builder is not supported yet. You can use the `.. only::` directive to skip it for now.

I will try to add latex support recently.

**Comment by SilverRainZ** [comment]
@rappdw  You can try `sphinxnotes-strike==1.1`, should fix this issue.

**Comment by rappdw** [comment]
Thanks! The issue is fixed.
